use_default_settings: true

server:
  secret_key: "хуйняхуйняхуйхуйчленписяпопасися"
  bind_address: "0.0.0.0"
  port: 8080
  base_url: https://localhost:8444/

search:
  safe_search: 0
  autocomplete: "duckduckgo"
  on_category_select: save
  ban_time_on_fail: 5
  upstream_timeout: 1.0

ui:
  theme: simple

engines:
  - name: google
    engine: google
    shortcut: go
    timeout: 0.7
    disabled: false

  - name: brave
    engine: brave
    shortcut: br
    timeout: 1.0
    disabled: false

  - name: duckduckgo
    engine: duckduckgo
    shortcut: dd
    timeout: 1.0
    disabled: false

  - name: qwant
    engine: qwant
    shortcut: qw
    timeout: 1.0
    disabled: false
